### ISSUE TITLE
Disable preview?

### ISSUE THREAD

**Issue by boetter** [matthewreagan/GIFPop#1]
I'd love to use this to resize massive GIFs made from capturing my screen. So they would be massive, as in really massive. I just tried with a 2320x1590 one, but it's unfortunately not possible to reach the controls when importing such a big fella because of the huge preview filling up my entire screen. Would it be possible to wish for preview to be disabled?

**Comment by matthewreagan** [comment]
@boetter Sure 👍 , I've pushed a fix for this so that the window doesn't automatically resize, so it should be more usable now with really big GIFs. Also added an optional checkbox to disable the preview animation which might be helpful to avoid slowing down the UI.

**Comment by igorwojda** [comment]
This seems not to be working with precompiled binnary
